/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/dist/types/global" />

// NOTE: This file should not be edited manually, but when its contents are changed,
// it should not be generated by Next.js.

// Extends Next.js environment types for custom needs.

// Custom environment variable types for process.env
declare namespace NodeJS {
  interface ProcessEnv {
    readonly NEXT_PUBLIC_BACKEND_URL: string;
    readonly NEXT_PUBLIC_AUTH_DOMAIN: string;
    readonly NEXT_PUBLIC_CLIENT_ID: string;
    readonly NEXT_PUBLIC_APP_ENVIRONMENT: 'development' | 'production' | 'staging';
  }
}

// Type declarations for raw imports (e.g., GLSL shaders)
declare module '*.glsl' {
  const content: string;
  export default content;
}

declare module '*.vert' {
  const content: string;
  export default content;
}

declare module '*.frag' {
  const content: string;
  export default content;
}